version: '3.8'

services:
  forwardarr:
    image: ghcr.io/ramseymcgrath/forwardarr:latest
    container_name: forwardarr
    user: 1000:1000
    volumes:
      - /data/docker/forwardarr/config/api_keys.json:/config/api_keys.json:ro
      - /data/docker/forwardarr/config/indexer_urls.json:/config/indexer_urls.json:ro
    environment:
      - INDEXER_URLS_JSON=/config/indexer_urls.json
      - API_KEYS_FILE=/config/api_keys.json
      - DD_DOGSTATSD_PORT=8125
      - DD_AGENT_HOST=10.0.0.166
    ports:
     - 6060:8080
    restart: unless-stopped
