name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Forwardarr Proxy Docker image
      run: docker build ./proxy --file Dockerfile --tag forwardarr:$(date +%s)
